name: Build Android Binary

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: pnpm install

      - name: Build web assets
        run: pnpm run build:static

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-${{ github.run_number }}
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Build Android AAB
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload Android AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab-${{ github.run_number }}
          path: android/app/build/outputs/bundle/release/app-release.aab